set(_CATKIN_CURRENT_PACKAGE "wheelleg_description_ver15")
set(wheelleg_description_ver15_VERSION "1.0.0")
set(wheelleg_description_ver15_MAINTAINER " <TODO@email.com>")
set(wheelleg_description_ver15_PACKAGE_FORMAT "2")
set(wheelleg_description_ver15_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver15_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver15_BUILDTOOL_DEPENDS "catkin")
set(wheelleg_description_ver15_BUILDTOOL_EXPORT_DEPENDS )
set(wheelleg_description_ver15_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver15_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver15_TEST_DEPENDS )
set(wheelleg_description_ver15_DOC_DEPENDS )
set(wheelleg_description_ver15_URL_WEBSITE "")
set(wheelleg_description_ver15_URL_BUGTRACKER "")
set(wheelleg_description_ver15_URL_REPOSITORY "")
set(wheelleg_description_ver15_DEPRECATED "")