set(_CATKIN_CURRENT_PACKAGE "wheelleg_description_ver13")
set(wheelleg_description_ver13_VERSION "1.0.0")
set(wheelleg_description_ver13_MAINTAINER " <TODO@email.com>")
set(wheelleg_description_ver13_PACKAGE_FORMAT "2")
set(wheelleg_description_ver13_BUILD_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver13_BUILD_EXPORT_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver13_BUILDTOOL_DEPENDS "catkin")
set(wheelleg_description_ver13_BUILDTOOL_EXPORT_DEPENDS )
set(wheelleg_description_ver13_EXEC_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver13_RUN_DEPENDS "roslaunch" "robot_state_publisher" "rviz" "joint_state_publisher_gui" "gazebo")
set(wheelleg_description_ver13_TEST_DEPENDS )
set(wheelleg_description_ver13_DOC_DEPENDS )
set(wheelleg_description_ver13_URL_WEBSITE "")
set(wheelleg_description_ver13_URL_BUGTRACKER "")
set(wheelleg_description_ver13_URL_REPOSITORY "")
set(wheelleg_description_ver13_DEPRECATED "")