#!/usr/bin/env sh
# generated from catkin/python/catkin/environment_cache.py

# based on a snapshot of the environment before and after calling the setup script
# it emulates the modifications of the setup script without recurring computations

# new environment variables

# modified environment variables
export CMAKE_PREFIX_PATH='/home/hyeongu/catkin_towr_backup/devel_isolated/wheelleg_description_ver13:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_examples:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_quadrotor:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_hyq:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_vis:/home/hyeongu/catkin_towr_backup/devel_isolated/towr_ros:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_states:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_msgs:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp:/home/hyeongu/catkin_towr/devel_isolated/xpp_examples:/home/hyeongu/catkin_towr/devel_isolated/xpp_quadrotor:/home/hyeongu/catkin_towr/devel_isolated/xpp_hyq:/home/hyeongu/catkin_towr/devel_isolated/xpp_vis:/home/hyeongu/catkin_towr/devel_isolated/towr_ros:/home/hyeongu/catkin_towr/devel_isolated/xpp_states:/home/hyeongu/catkin_towr/devel_isolated/xpp_msgs:/home/hyeongu/catkin_towr/devel_isolated/xpp:/opt/ros/noetic:/home/hyeongu/catkin_towr_backup/devel_isolated/towr:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt:/home/hyeongu/catkin_towr_backup/devel_isolated/towr:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt:/home/hyeongu/catkin_towr/devel_isolated/towr:/home/hyeongu/catkin_towr/devel_isolated/ifopt'
export LD_LIBRARY_PATH='/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_examples/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_quadrotor/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_hyq/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_vis/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/towr_ros/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_states/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_msgs/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_examples/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_quadrotor/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_hyq/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_vis/lib:/home/hyeongu/catkin_towr/devel_isolated/towr_ros/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_states/lib:/home/hyeongu/catkin_towr/devel_isolated/xpp_msgs/lib:/opt/ros/noetic/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib/x86_64-linux-gnu:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib/x86_64-linux-gnu:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib:/home/hyeongu/catkin_towr/devel_isolated/towr/lib:/home/hyeongu/catkin_towr/devel_isolated/ifopt/lib'
export PATH='/opt/ros/noetic/bin:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/bin:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
export PKG_CONFIG_PATH='/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_examples/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_quadrotor/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_hyq/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_vis/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/towr_ros/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_states/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_msgs/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_examples/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_quadrotor/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_hyq/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_vis/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/towr_ros/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_states/lib/pkgconfig:/home/hyeongu/catkin_towr/devel_isolated/xpp_msgs/lib/pkgconfig:/opt/ros/noetic/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib/x86_64-linux-gnu/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib/pkgconfig:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib/x86_64-linux-gnu/pkgconfig'
export PYTHONPATH='/home/hyeongu/catkin_towr_backup/devel_isolated/towr_ros/lib/python3/dist-packages:/home/hyeongu/catkin_towr_backup/devel_isolated/xpp_msgs/lib/python3/dist-packages:/home/hyeongu/catkin_towr/devel_isolated/towr_ros/lib/python3/dist-packages:/home/hyeongu/catkin_towr/devel_isolated/xpp_msgs/lib/python3/dist-packages:/opt/ros/noetic/lib/python3/dist-packages:/home/hyeongu/catkin_towr_backup/devel_isolated/towr/lib/python3/dist-packages:/home/hyeongu/catkin_towr_backup/devel_isolated/ifopt/lib/python3/dist-packages'
export ROSLISP_PACKAGE_DIRECTORIES="/home/hyeongu/catkin_towr_backup/devel_isolated/wheelleg_description_ver13/share/common-lisp:$ROSLISP_PACKAGE_DIRECTORIES"
export ROS_PACKAGE_PATH="/home/hyeongu/catkin_towr_backup/src/wheelleg_description_ver13:$ROS_PACKAGE_PATH"